language: node_js
node_js:
 - '11.2'
install:
  - npm install -g codecov
  - npm install
script:
- npm run start -- --testMode
- npm run demo
- npm run coverage
- codecov
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL